### ISSUE TITLE
Foreman can't start

### ISSUE THREAD

**Issue by idoo** [oh-my-fish/plugin-bundler#6]
```
bundler/rubygems_integration.rb:292:in `block in replace_gem': foreman is not part of the bundle. Add it to Gemfile. (Gem::LoadError)
from /.rbenv/versions/2.2.3/bin/foreman:22:in `<main>'
```

But in foreman github page https://github.com/ddollar/foreman
exist notice: `Ruby users should take care not to install foreman in their project's Gemfile.`
Any ideas how to fix this?

**Comment by bpinto** [comment]
We have `foreman` here: https://github.com/oh-my-fish/plugin-bundler/blob/master/bundler.fish#L7

Probably if you remove it from there, it is going to work. Could you try that?

**Comment by idoo** [comment]
@bpinto yes, it's solve my problem

**Comment by bobthecow** [comment]
yeah, makes sense, since you're supposed to use a global install for foreman.
